### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com until 2020-12-31

### ISSUE THREAD

**Issue by christiansiegel** [baloise/corellia#119]
travis-ci.**org** will be closed down December 31st, 2020

Announcement: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom
Migration guide: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by MarkusTiede** [comment]
Corellia has been ported to Github Actions a while ago - it's though still been active in travis; I've now deactivated the settings for corellia on travis-ci.org side:

![Bildschirmfoto 2020-12-03 um 10 16 29](https://user-images.githubusercontent.com/1764012/100989163-d27d1280-3550-11eb-99f9-5de795a4aa7b.png)

In my opinion there nothing else do to for corellia regarding the travis migration. Please feel free to reopen otherwise.

**Comment by MarkusTiede** [comment]
Parent issue: https://github.com/baloise/open-source/issues/274
